### ISSUE TITLE
Slack icon integration alternative

### ISSUE THREAD

**Issue by ryanlalchand** [codeyoungstown/next-codeyoungstown.com#10]
old slack button from current site doesn't work

**Comment by ryanlalchand** [comment]
Ideas: copy script to project and edit so that it renders in the right spot and _not_ off the page in the white zone

**Comment by JoeDuncko** [comment]
Closing because we are no longer using Slackin, see https://github.com/rauchg/slackin/issues/417#issuecomment-1474890525
