### ISSUE TITLE
tailwind won't allow me to change hover text color for Socials.tsx

### ISSUE THREAD

**Issue by ryanlalchand** [codeyoungstown/next-codeyoungstown.com#15]
only `hover:text-blue` works, no other color. In fact, Intellisense stops working ....

**Comment by JoeDuncko** [comment]
Hm... many colors that I expected to work don't work, but `hover:text-gray` does. Looking further in...

**Comment by JoeDuncko** [comment]
Copying the Telegram convo below for posterity

> 
> Ryan Lalchand, [Jul 9, 2022 at 5:16:58 PM]:
> my only guess is that in tailwind.config i explicitly defined custom sitewide gray and blue
> 
> Joe, [Jul 9, 2022 at 5:18:23 PM]:
> Yup! deleting the theme colors config fixed using all tailwindcss colors
> 
> ![telegram-cloud-photo-size-1-5066986873343290095-y](https://user-images.githubusercontent.com/6749768/178123128-b0eb526a-f870-4493-90e9-8e64d7d8f3e9.jpg)
> 
> Ryan Lalchand, [Jul 9, 2022 at 5:19:12 PM]:
> why would that break it though???
> 
> Joe, [Jul 9, 2022 at 5:20:30 PM]:
> Looks like they expect you to specify all versions of the colors yourself if you are gunna use the theme section, it doesn't generate them on its own, which I would have expected if they aren't specified
> 
> Theme Configuration - Tailwind CSS
> Customizing the default theme for your project.
> 
> https://tailwindcss.com/docs/theme#extending-the-default-theme
> 
> Looks like you can instead extend the existing theme. So if you want to add a code-youngstown-gray, but keep the expected built in colors, you can do that.
> 
> How weird and not the smart defaults I would have expected
